apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - apps.yaml
  - infrastructure.yaml
  - ../../infrastructure
  - namespace.yaml
  - nginx.yaml
  - image-automation.yaml
images:
- name:dbsmouse/nginx
  newTag: test-5 # {"$imagepolicy": "flux-system:platform-frontend-release:tag"}