apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base/podinfo
  - nginx.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
images:
  - name: dbsmouse/nginx
    newTag: test-7 # {"$imagepolicy": "flux-system:dbsmouse-nginx-development:tag"}
configMapGenerator:
- name: common-configs
  behavior: merge
  envs:
  - config.properties
  options:
    disableNameSuffixHash: true
